language: go

go:
- 1.13.x
- master

sudo: true

dist: bionic

env:
  - GO111MODULE=on

# disable install as we run everything ourselves
install: true

before_script:
  - sudo sh -c "sed -i s/bionic/eoan/g /etc/apt/sources.list && apt update && apt --yes full-upgrade"
  - sudo apt install libzfslinux-dev
  - sudo modprobe zfs

script:
  - echo '============== Tests ==============' >/dev/null
  - sudo -E env "PATH=$PATH" go test -coverprofile=coverage.txt -covermode=atomic ./...
  - sudo -E env "PATH=$PATH" go test -race ./...
  - echo '============== Benchmarks ==============' >/dev/null
  - sudo -E env "PATH=$PATH" go test -bench -run=Benchmark ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
