name: Update master branch automatically
on:
  push:
    branch: test

jobs:
  update-po:
    name: Update po files
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      # Install go
      - uses: actions/setup-go@v1
        with:
          go-version: '1.13.x'
      - name: Install required dependencies
        run: apt install -y gettext
      # Update po if needed
      - name: Check and update po files
        run: |
          echo "::set-env name=pomodified::false"
          go generate ./internal/i18n/
          # Exclude line diffs only
          #MODIFIED=$(git difftool -y -x "diff -Nup -I '^#: '" po/)
          if [ -n "$MODIFIED" ]; then
              echo "::set-env name=pomodified::true"
          fi
      - name: test
        if: steps.test.env.pomodified == "true"
        run: echo "PO modified"
      - name: test2
        if: steps.test2.env.pomodified == "true"
        run: echo "PO NOT modified"